### ISSUE TITLE
参数解析错误

### ISSUE THREAD

**Issue by xiaohan2013** [WildDogTeam/sms-sdk-python#1]
`
def sendSmsWilddog():
    appId = 'xxxxxxx';
    APP_KEY = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
    smsclinet = SmsClient(appId, APP_KEY)

    templateId = 'xxxxx'
    mobile = '13288888888'
    params = "['123456']"
    res = smsclinet.send_code(mobile, templateId, params)

`
以上，是我的调用代码。
如果我使用params = None的方式调用是没有问题，但是当我使用传参数时报了这个错误。

`{"errcode": 70231,"message": "sms params parse error, please check it"}`

我使用的python3.4.5

**Comment by jnduan** [comment]
Will fix it tomorrow, thanks.

**Comment by jnduan** [comment]
Fixed in release V1.0.2
